---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katib-mysql-pv-claim-1-6
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
